bookmarks/bookmarks/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
# from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social.apps.django_app.urls', namespace='social')),
    path('images/', include('images.urls')),
]


if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bookmarks/images/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/',views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
]

bookmarks/images/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
User = get_user_model()
from django.utils.text import slugify
# from django.core.urlresolvers import 
# from django.http import rever
from django.urls import reverse




class Image(models.Model):
    user = models.ForeignKey(User,related_name='images_created' , on_delete=models.CASCADE)
    users_like = models.ManyToManyField(User,  related_name='images_liked', blank=True )
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
    blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to='images/%Y/%m/%d')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True,
    db_index=True)
    total_likes = models.PositiveIntegerField(db_index=True,default=0)
    
    class Meta:
        ordering = ['-id']
    
    def __str__(self):
        return self.title

    


    def get_absolute_url(self):
        return reverse('detail', args=[self.id, self.slug])


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            super(Image, self).save(*args, **kwargs)


bookmarks/images/forms.py
from django import forms
from .models import Image
# from urllib import request
from urllib.request import Request, urlopen
from django.core.files.base import ContentFile
from django.utils.text import slugify


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {
        'url': forms.HiddenInput,
        }

        def clean_url(self):
            url = self.cleaned_data['url']
            valid_extensions = ['jpg', 'jpeg']
            extension = url.rsplit('.', 1)[1].lower()
            if extension not in valid_extensions:
                raise forms.ValidationError('The given URL does not match valid image extensions.')
            return url

    def save(self, force_insert=False, force_update=False, commit=True):
        image = super(ImageCreateForm, self).save(commit=False)
        image_url = self.cleaned_data['url']
        image_name = '{}.{}'.format(slugify(image.title),
        
        image_url.rsplit('.', 1)[1].lower())
        req = Request(
            url=image_url, 
            headers={'User-Agent': 'Mozilla/5.0'}
        )
        # print(image_url)
        # download image from the given URL
        print("form save method")
        response = urlopen(req)

        print("request opened")
        image.image.save(image_name,
        ContentFile(response.read()),
        save=False)
        if commit:
            image.save()
        return image

bookmarks/images/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ImageCreateForm
from django.shortcuts import get_object_or_404
from .models import Image
from django.http import JsonResponse
from django.views.decorators.http import require_POST
# from common.decorators import ajax_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from actions.utils import create_action

@login_required
def image_create(request):
    if request.method == 'POST':
        # form is sent
        print("request is sent")
        form = ImageCreateForm(data=request.POST , files = request.FILES)
        if form.is_valid():
            # form data is valid
            cd = form.cleaned_data
            new_item = form.save(commit=False)
            # assign current user to the item
            new_item.user = request.user
            new_item.save()
            create_action(request.user, 'bookmarked image', new_item)
            messages.success(request, 'Image added successfully')
            # redirect to new created item detail view
            return redirect(new_item.get_absolute_url())
    else:
    # build form with data provided by the bookmarklet via GET
        form = ImageCreateForm(data=request.GET)
    return render(request,
    'images/image/create.html',
    {'section': 'images',
    'form': form})


def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    return render(request,
    'images/image/detail.html',
    {'section': 'images',
    'image': image})

# @ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status':'ok'})
        except Exception as e:
            print(e)
            pass
    return JsonResponse({'status':'ko'})



def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

@login_required
def image_list(request):
    images = Image.objects.all()
    paginator = Paginator(images, 8)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
    # If page is not an integer deliver the first page
        images = paginator.page(1)
    except EmptyPage:
        if is_ajax(request):
        # If the request is AJAX and the page is out of range
        # return an empty page
            return HttpResponse('')
        # If page is out of range deliver last page of results
        images = paginator.page(paginator.num_pages)
    if is_ajax(request):
        return render(request,
        'images/image/list_ajax.html',
        {'section': 'images', 'images': images})
    return render(request,
    'images/image/list.html',
    {'section': 'images', 'images': images})

bookmarks/images/templates/images/image/create.html
{% extends "base.html" %}
{% block title %}Bookmark an image{% endblock %}
{% block content %}
{% include 'account/form_errors.html'  %}
{% include 'account/messages.html'  %}


<div class="container">
    <div class="row justify-content-center my-5">
        <div class="col-12 col-md-8 col-lg-6">
            <h1 class="text-start mb-4 fw-bolder">
                Bookmark an image
            </h1>
            {% load thumbnail %}
                {% thumbnail request.GET.url "300" as im %}
                <img src="{{ im.url }}" class="image-detail mb-4 text-center" >
                
            {% endthumbnail %}
            <form action="{% url 'create' %}" method="post" enctype="multipart/form-data " class="row g-3 needs-validation" novalidate>
                {% csrf_token %}
                <div class="col-12 col-lg-8">
                    <label for="id_title" class="form-label">Title</label>
                    <input type="text" name="title" maxlength="200" required id="id_title" required="" class="form-control rounded-0 bg-light">
                    <div class="invalid-feedback">
                        Please enter a valid title.
                    </div>
                </div>
                <div class="col-12 col-lg-8">
                    <label for="id_description" class="form-label">Description</label>
                    <textarea name="description" cols="40" rows="10" id="id_description" class="form-control rounded-0 bg-light" required=""></textarea>
                    <div class="invalid-feedback">
                        Please enter a valid description.
                    </div>
                </div>

                <input type="hidden" name="url" id="id_url" value="{{ request.GET.url }}">
                <div class="col-12 col-lg-8">
                    <input type="submit" value="Bookmark it!" class="btn btn-success rounded-0 text-uppercase p-2">
                </div>
                
            </form>
            
        </div>
    </div>
</div>
{% endblock %}



{% block extra_js %}
<script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
(function () {
  'use strict'

  // Fetch all the forms we want to apply custom Bootstrap validation styles to
  var forms = document.querySelectorAll('.needs-validation')

  // Loop over them and prevent submission
  Array.prototype.slice.call(forms)
    .forEach(function (form) {
      form.addEventListener('submit', function (event) {
        if (!form.checkValidity()) {
          event.preventDefault()
          event.stopPropagation()
        }

        form.classList.add('was-validated')
      }, false)
    })
})()
</script>
{% endblock extra_js %}

bookmarks/images/templates/images/image/detail.html
{% extends "base.html" %}
{% block title %}{{ image.title }}{% endblock %}
{% block content %}




<div class="container">
    <div class="row justify-content-center my-5">
        <div class="col-12">
            <h1 class="text-center mb-4 fw-bolder">
                {{ image.title }}
            </h1>
        </div>
    </div>
    <div class="row justify-content-center my-5">
        <div class="col-12 col-lg-7">
            {% load thumbnail %}
            {% thumbnail image.image "650" as im %}
                <a href="{{ image.image.url }}"><img src="{{ im.url }}" class="img-fluid"></a>
            {% endthumbnail %}
        </div>
        <div class="col-12 col-lg-4">
            {% with total_likes=image.users_like.count users_like=image.users_like.all %}
            <div class="image-info my-4">
            <div>
                <span class="count rounded-pill btn btn-outline-success px-5">
                    <span class="total">{{ total_likes }}</span> like{{ total_likes|pluralize }}
                </span>
                <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button btn btn-success p-2 px-5 rounded-0 text-uppercase ms-4">
                    {% if request.user not in users_like %} Like {% else %} Unlike {% endif %}</a>
            </div>
            <div>
                <p>
                    {{ image.description|linebreaks }}
                </p>
            </div>
            
            </div>
            <div class="image-likes">
                {% for user in image.users_like.all %}
                    <div>
                        <img src="{{ user.profile.photo.url }}" width="250px" height="250px">
                        <p class="h2 fw-bolder text-success">{{ user.first_name }}</p>
                    </div>
                    {% empty %}
                    <div>
                        <p>
                            Nobody likes this image yet.
                        </p>
                    </div>
                {% endfor %}
            </div>
            {% endwith %}

        </div>
    </div>
</div>



{% endblock %}

{% block extra_js %}
<script>
    $(document).ready(function(){
        $('a.like').click(function(e){
e.preventDefault();
$.post('{% url "like" %}',
{
id: $(this).data('id'),
action: $(this).data('action')
},
function(data){
if (data['status'] == 'ok')
{
var previous_action = $('a.like').data('action');
// toggle data-action
$('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
// toggle link text
$('a.like').text(previous_action == 'like' ? 'Unlike' :'Like');
// update total likes
var previous_likes = parseInt($('span.count .total').
text());
$('span.count .total').text(previous_action == 'like' ?
previous_likes + 1 : previous_likes - 1);
}
}
);
});
    })
</script>
{% endblock extra_js %}

bookmarks/images/templates/images/image/list.html
{% extends "base.html" %}
{% block title %}Images bookmarked{% endblock %}
{% block content %}
<h1>Images bookmarked</h1>
<div id="image-list">
{% include "images/image/list_ajax.html" %}
</div>
{% endblock %}

{% block extra_js %}
<script>
    $(document).ready(function(){
        var page = 1;
        var empty_page = false;
        var block_request = false;
        $(window).scroll(function() {
        var margin = $(document).height() - $(window).height() - 200;
        if ($(window).scrollTop() > margin && empty_page == false &&
        block_request == false) {
        block_request = true;
        page += 1;
        $.get('?page=' + page, function(data) {
        if(data == '') {
        empty_page = true;
        }
        else {
        block_request = false;
        $('#image-list').append(data);
        }
        });
        }
        });
    });
</script>
{% endblock extra_js %}

bookmarks/images/templates/images/image/list_ajax.html
{% load thumbnail %}
{% for image in images %}
<div class="image my-4">
<a href="{{ image.get_absolute_url }}" class="card-link fw-bolder text-success">
{% thumbnail image.image "300x300" crop="100%" as im %}
<a href="{{ image.get_absolute_url }}">
<img src="{{ im.url }}">
</a>
{% endthumbnail %}
</a>
<div class="info">
<a href="{{ image.get_absolute_url }}" class="title card-link fw-bolder text-success fs-3">
{{ image.title }}
</a>
</div>
</div>
{% endfor %}